{
 "archived": false,
 "branch": "main",
 "conda-forge.yml": {
  "conda_build": {
   "pkg_format": "2"
  },
  "conda_forge_output_validation": true,
  "github": {
   "branch_name": "main",
   "tooling_branch_name": "main"
  }
 },
 "feedstock_name": "pytest-rerunfailures",
 "hash_type": "sha256",
 "linux_64_meta_yaml": {
  "about": {
   "home": "https://github.com/pytest-dev/pytest-rerunfailures",
   "license": "MPL-2.0",
   "license_family": "OTHER",
   "license_file": "LICENSE",
   "summary": "pytest plugin to re-run tests to eliminate flaky failures"
  },
  "build": {
   "noarch": "python",
   "number": "0",
   "script": "PYTHON -m pip install . -vv"
  },
  "extra": {
   "recipe-maintainers": [
    "nicoddemus",
    "pg-hbk",
    "sy-hbk"
   ]
  },
  "package": {
   "name": "pytest-rerunfailures",
   "version": "14.0"
  },
  "requirements": {
   "host": [
    "pip",
    "setuptools >=40",
    "python >=3.8"
   ],
   "run": [
    "packaging >=17.1",
    "importlib-metadata >=1",
    "pytest >=7.2",
    "python >=3.8",
    "setuptools"
   ]
  },
  "source": {
   "sha256": "4a400bcbcd3c7a4ad151ab8afac123d90eca3abe27f98725dc4d9702887d2e92",
   "url": "https://pypi.io/packages/source/p/pytest-rerunfailures/pytest-rerunfailures-14.0.tar.gz"
  },
  "test": {
   "imports": [
    "pytest_rerunfailures"
   ]
  }
 },
 "linux_64_requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python",
    "setuptools"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "importlib-metadata",
    "packaging",
    "pytest",
    "python",
    "setuptools"
   ]
  },
  "test": {
   "__set__": true,
   "elements": []
  }
 },
 "meta_yaml": {
  "about": {
   "home": "https://github.com/pytest-dev/pytest-rerunfailures",
   "license": "MPL-2.0",
   "license_family": "OTHER",
   "license_file": "LICENSE",
   "summary": "pytest plugin to re-run tests to eliminate flaky failures"
  },
  "build": {
   "noarch": "python",
   "number": "0",
   "script": "PYTHON -m pip install . -vv"
  },
  "extra": {
   "recipe-maintainers": [
    "nicoddemus",
    "pg-hbk",
    "sy-hbk"
   ]
  },
  "package": {
   "name": "pytest-rerunfailures",
   "version": "14.0"
  },
  "requirements": {
   "host": [
    "pip",
    "setuptools >=40",
    "python >=3.8"
   ],
   "run": [
    "packaging >=17.1",
    "importlib-metadata >=1",
    "pytest >=7.2",
    "python >=3.8",
    "setuptools"
   ]
  },
  "source": {
   "sha256": "4a400bcbcd3c7a4ad151ab8afac123d90eca3abe27f98725dc4d9702887d2e92",
   "url": "https://pypi.io/packages/source/p/pytest-rerunfailures/pytest-rerunfailures-14.0.tar.gz"
  },
  "test": {
   "imports": [
    "pytest_rerunfailures"
   ]
  }
 },
 "name": "pytest-rerunfailures",
 "outputs_names": {
  "__set__": true,
  "elements": [
   "pytest-rerunfailures"
  ]
 },
 "parsing_error": false,
 "platforms": [
  "linux_64"
 ],
 "pr_info": {
  "__lazy_json__": "pr_info/pytest-rerunfailures.json"
 },
 "raw_meta_yaml": "{% set name = \"pytest-rerunfailures\" %}\n{% set version = \"14.0\" %}\n\npackage:\n  name: {{ name|lower }}\n  version: {{ version }}\n\nsource:\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz\n  sha256: 4a400bcbcd3c7a4ad151ab8afac123d90eca3abe27f98725dc4d9702887d2e92\n\nbuild:\n  number: 0\n  noarch: python\n  script: {{ PYTHON }} -m pip install . -vv\n\nrequirements:\n  host:\n    - pip\n    - setuptools >=40\n    - python >=3.8\n  run:\n    - packaging >=17.1\n    - importlib-metadata >=1\n    - pytest >=7.2\n    - python >=3.8\n    - setuptools\n\ntest:\n  imports:\n    - pytest_rerunfailures\n\nabout:\n  home: https://github.com/pytest-dev/pytest-rerunfailures\n  license: MPL-2.0\n  license_family: OTHER\n  license_file: LICENSE\n  summary: pytest plugin to re-run tests to eliminate flaky failures\n\nextra:\n  recipe-maintainers:\n    - nicoddemus\n    - pg-hbk\n    - sy-hbk\n",
 "req": {
  "__set__": true,
  "elements": [
   "importlib-metadata",
   "packaging",
   "pip",
   "pytest",
   "python",
   "setuptools"
  ]
 },
 "requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python",
    "setuptools"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "importlib-metadata",
    "packaging",
    "pytest",
    "python",
    "setuptools"
   ]
  },
  "test": {
   "__set__": true,
   "elements": []
  }
 },
 "strong_exports": false,
 "total_requirements": {
  "build": {
   "__set__": true,
   "elements": []
  },
  "host": {
   "__set__": true,
   "elements": [
    "pip",
    "python >=3.8",
    "setuptools >=40"
   ]
  },
  "run": {
   "__set__": true,
   "elements": [
    "importlib-metadata >=1",
    "packaging >=17.1",
    "pytest >=7.2",
    "python >=3.8",
    "setuptools"
   ]
  },
  "test": {
   "__set__": true,
   "elements": []
  }
 },
 "url": "https://pypi.io/packages/source/p/pytest-rerunfailures/pytest-rerunfailures-14.0.tar.gz",
 "version": "14.0",
 "version_pr_info": {
  "__lazy_json__": "version_pr_info/pytest-rerunfailures.json"
 }
}