{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51106"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 2,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 3,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python38"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": null,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 2,
    "migrator_version": 0,
    "name": "python39"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 7,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy37"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 9,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "gsl27"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 10,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51121"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 11,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python310"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 13,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "OSXArm",
    "migrator_version": 1,
    "name": "arm osx addition"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 14,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51122"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 15,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python311"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 16,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1681580477.3552814,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51140"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 18,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51140"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 19,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51141"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 20,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "hdf51142"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [
     {
      "name": "automerge"
     }
    ],
    "number": 21,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python312"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2023.09.27.16.11.26",
 "pre_pr_migrator_attempts": {
  "pypy37-windows": 1,
  "pypy38": 614,
  "python39": 1
 },
 "pre_pr_migrator_status": {
  "pypy37-windows": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/1422837730\">bot CI job</a>): master: ['win_64_numpy1.19python3.7.____73_pypy: Encountered problems while solving:\\n  - package xraylib-4.1.0-py36he8b1a61_0 requires python >=3.6,<3.7.0a0, but none of the providers can be installed\\n']",
  "pypy38": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/7552174667'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_numpy1.22python3.9.____73_pypy: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 hdf5 1.14.3.*  is installable and it requires\n\u2502  \u2514\u2500 libzlib >=1.2.13,<1.3.0a0  with the potential options\n\u2502     \u251C\u2500 libzlib 1.2.13 would require\n\u2502     \u2502  \u2514\u2500 zlib 1.2.13 *_4, which can be installed;\n\u2502     \u2514\u2500 libzlib 1.2.13 would require\n\u2502        \u2514\u2500 zlib 1.2.13 *_5, which can be installed;\n\u251C\u2500 python 3.9.* *_73_pypy is installable and it requires\n\u2502  \u2514\u2500 python_abi 3.9 *_pypy39_pp73, which can be installed;\n\u251C\u2500 xraylib 4.1.*  is not installable because there are no viable options\n\u2502  \u251C\u2500 xraylib [4.1.0|4.1.1] would require\n\u2502  \u2502  \u2514\u2500 python >=3.6,<3.7.0a0  but there are no viable options\n\u2502  \u2502     \u251C\u2500 python [3.6.0|3.6.1|...|3.6.9] conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 python 3.6.3 would require\n\u2502  \u2502     \u2502  \u2514\u2500 zlib 1.2.8 , which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u2514\u2500 python [3.6.3|3.6.4|3.6.5] would require\n\u2502  \u2502        \u2514\u2500 zlib 1.2.11 , which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3] would require\n\u2502  \u2502  \u2514\u2500 python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3|4.1.4] would require\n\u2502  \u2502  \u2514\u2500 python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3|4.1.4] would require\n\u2502  \u2502  \u2514\u2500 python_abi 3.9.* *_cp39 but there are no viable options\n\u2502  \u2502     \u251C\u2500 python_abi 3.9 conflicts with any installable versions previously reported;\n\u2502  \u2502     \u2514\u2500 python_abi 3.9 would require\n\u2502  \u2502        \u2514\u2500 python 3.9.* *_cpython, which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.1|4.1.2|4.1.3|4.1.4] would require\n\u2502  \u2502  \u2514\u2500 python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.3|4.1.4] would require\n\u2502  \u2502  \u2514\u2500 python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;\n\u2502  \u2514\u2500 xraylib [4.1.3|4.1.4] would require\n\u2502     \u2514\u2500 python_abi 3.12.* *_cp312, which requires\n\u2502        \u2514\u2500 python 3.12.* *_cpython, which conflicts with any installable versions previously reported;\n\u2514\u2500 zlib 1.2.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>osx_64_numpy1.22python3.9.____73_pypy: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 hdf5 1.14.3.*  is installable and it requires\n\u2502  \u2514\u2500 libzlib >=1.2.13,<1.3.0a0  with the potential options\n\u2502     \u251C\u2500 libzlib 1.2.13 would require\n\u2502     \u2502  \u2514\u2500 zlib 1.2.13 *_4, which can be installed;\n\u2502     \u2514\u2500 libzlib 1.2.13 would require\n\u2502        \u2514\u2500 zlib 1.2.13 *_5, which can be installed;\n\u251C\u2500 python 3.9.* *_73_pypy is installable and it requires\n\u2502  \u2514\u2500 python_abi 3.9 *_pypy39_pp73, which can be installed;\n\u251C\u2500 xraylib 4.1.*  is not installable because there are no viable options\n\u2502  \u251C\u2500 xraylib [4.1.0|4.1.1] would require\n\u2502  \u2502  \u2514\u2500 python >=3.6,<3.7.0a0  but there are no viable options\n\u2502  \u2502     \u251C\u2500 python [3.6.0|3.6.1|...|3.6.9] conflicts with any installable versions previously reported;\n\u2502  \u2502     \u251C\u2500 python 3.6.3 would require\n\u2502  \u2502     \u2502  \u2514\u2500 zlib 1.2.8 , which conflicts with any installable versions previously reported;\n\u2502  \u2502     \u2514\u2500 python [3.6.3|3.6.4|3.6.5] would require\n\u2502  \u2502        \u2514\u2500 zlib 1.2.11 , which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3] would require\n\u2502  \u2502  \u2514\u2500 python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3|4.1.4] would require\n\u2502  \u2502  \u2514\u2500 python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3|4.1.4] would require\n\u2502  \u2502  \u2514\u2500 python_abi 3.9.* *_cp39 but there are no viable options\n\u2502  \u2502     \u251C\u2500 python_abi 3.9 conflicts with any installable versions previously reported;\n\u2502  \u2502     \u2514\u2500 python_abi 3.9 would require\n\u2502  \u2502        \u2514\u2500 python 3.9.* *_cpython, which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.1|4.1.2|4.1.3|4.1.4] would require\n\u2502  \u2502  \u2514\u2500 python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;\n\u2502  \u251C\u2500 xraylib [4.1.3|4.1.4] would require\n\u2502  \u2502  \u2514\u2500 python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;\n\u2502  \u2514\u2500 xraylib [4.1.3|4.1.4] would require\n\u2502     \u2514\u2500 python_abi 3.12.* *_cp312, which requires\n\u2502        \u2514\u2500 python 3.12.* *_cpython, which conflicts with any installable versions previously reported;\n\u2514\u2500 zlib 1.2.*  is not installable because it conflicts with any installable versions previously reported.</pre><pre>win_64_numpy1.22python3.9.____73_pypy: Could not solve for environment specs\nThe following packages are incompatible\n\u251C\u2500 python 3.9.* *_73_pypy is installable and it requires\n\u2502  \u2514\u2500 python_abi 3.9 *_pypy39_pp73, which can be installed;\n\u2514\u2500 xraylib 4.1.*  is not installable because there are no viable options\n   \u251C\u2500 xraylib [4.1.0|4.1.1] would require\n   \u2502  \u2514\u2500 python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;\n   \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3] would require\n   \u2502  \u2514\u2500 python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;\n   \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3|4.1.4] would require\n   \u2502  \u2514\u2500 python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;\n   \u251C\u2500 xraylib [4.1.0|4.1.1|4.1.2|4.1.3|4.1.4] would require\n   \u2502  \u2514\u2500 python_abi 3.9.* *_cp39 but there are no viable options\n   \u2502     \u251C\u2500 python_abi 3.9 conflicts with any installable versions previously reported;\n   \u2502     \u2514\u2500 python_abi 3.9 would require\n   \u2502        \u2514\u2500 python 3.9.* *_cpython, which conflicts with any installable versions previously reported;\n   \u251C\u2500 xraylib [4.1.1|4.1.2|4.1.3|4.1.4] would require\n   \u2502  \u2514\u2500 python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;\n   \u251C\u2500 xraylib [4.1.3|4.1.4] would require\n   \u2502  \u2514\u2500 python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;\n   \u2514\u2500 xraylib [4.1.3|4.1.4] would require\n      \u2514\u2500 python_abi 3.12.* *_cp312, which requires\n         \u2514\u2500 python 3.12.* *_cpython, which conflicts with any installable versions previously reported.\n                </pre>\n                </div>\n                </details>",
  "python39": "bot error: master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 1035, in main\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 221, in run\n    eval_cmd(\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 183, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.8/subprocess.py\", line 444, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n"
 },
 "smithy_version": "3.26.3"
}