{
 "bad": false,
 "new_version": "8.477.24007",
 "new_version_attempts": {
  "3.143.20326": 1,
  "3.151.20327": 1,
  "4.20.21059": 1,
  "4.23.21108": 1,
  "4.3.20340": 1,
  "5.20.21182": 1,
  "5.23.21182": 1,
  "5.44.21241": 1,
  "7.111.22021": 1,
  "7.114.22021": 1,
  "7.121.22022": 1,
  "7.124.22022": 1,
  "7.126.22022": 2,
  "7.132.22039": 1,
  "7.141.22057": 1,
  "7.142.22057": 2,
  "7.149.22086": 1,
  "7.163.22119": 1,
  "7.173.22126": 0,
  "7.217.22307": 1,
  "7.230.22310": 2.6000000000000005,
  "7.238.22316": 1.4,
  "7.252.22317": 1.5999999999999999,
  "7.272.22339": 0.19999999999999996,
  "7.279.22339": 3.8000000000000016,
  "7.310.22362": 1.2,
  "7.330.23004": 1,
  "7.331.23005": 0.5999999999999999,
  "7.333.23006": 0.19999999999999996,
  "7.340.23006": 1,
  "7.341.23006": 3,
  "7.346.23011": 8,
  "7.358.23070": 4,
  "7.365.23080": 4,
  "7.368.23092": 6,
  "7.371.23118": 4,
  "7.374.23120": 3,
  "7.378.23124": 3,
  "7.385.23129": 3,
  "7.4.21313": 1,
  "7.403.23150": 3,
  "8.407.23153": 7,
  "8.411.23165": 1,
  "8.412.23165": 3,
  "8.417.23168": 7,
  "8.425.23207": 12,
  "8.434.23241": 5,
  "8.438.23256": 5,
  "8.440.23265": 3,
  "8.444.23276": 3,
  "8.445.23282": 5,
  "8.451.23305": 6,
  "8.456.23316": 22,
  "8.477.24007": 7
 },
 "new_version_errors": {
  "7.230.22310": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3420918262\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-kwargs 7.230.22310.*\\n']",
  "7.238.22316": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3452206473\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-kwargs 7.238.22316.*\\n']",
  "7.252.22317": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3457900779\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-kwargs 7.252.22317.*\\n']",
  "7.272.22339": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3615889992\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-imports 7.265.22338.*\\n  - nothing provides requested mo-dots 9.266.22338.*\\n  - nothing provides requested mo-future 6.265.22338.*\\n  - nothing provides requested mo-kwargs 7.271.22339.*\\n']",
  "7.279.22339": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3775845727\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-dots 9.279.22339.*\\n  - nothing provides requested mo-kwargs 7.279.22339.*\\n']",
  "7.310.22362": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3791294481\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-kwargs 7.310.22362.*\\n']",
  "7.331.23005": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3847336493\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-dots 9.331.23005.*\\n  - nothing provides requested mo-kwargs 7.331.23005.*\\n']",
  "7.333.23006": "not solvable (<a href=\"https://github.com/regro/autotick-bot/actions/runs/3852644142\">bot CI job</a>): main: ['linux_64_: Encountered problems while solving:\\n  - nothing provides requested mo-dots 9.331.23005.*\\n  - nothing provides requested mo-kwargs 7.331.23005.*\\n']",
  "7.340.23006": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.340.23006' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.341.23006": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.341.23006' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.346.23011": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.346.23011' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.358.23070": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.358.23070' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.365.23080": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.365.23080' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.368.23092": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.368.23092' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.371.23118": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.371.23118' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.374.23120": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.374.23120' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.378.23124": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.378.23124' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.385.23129": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.385.23129' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "7.403.23150": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '7.403.23150' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.407.23153": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.407.23153' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.411.23165": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.411.23165' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.412.23165": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.412.23165' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.417.23168": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.417.23168' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.425.23207": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.425.23207' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.434.23241": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.434.23241' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.438.23256": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.438.23256' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.440.23265": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.440.23265' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.444.23276": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.444.23276' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.445.23282": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.445.23282' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.451.23305": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.451.23305' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.456.23316": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.456.23316' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n",
  "8.477.24007": "The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '8.477.24007' to make sure they exist!\n\nWe also found the following errors:\n\n - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz'\n"
 }
}